{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "${{ values.service_name }}.fullname" . }}-secrets
  labels:
    {{- include "${{ values.service_name }}.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secrets.managedIdentityId | quote }}
    keyvaultName: {{ .Values.secrets.keyVaultName | quote }}
    tenantId: {{ .Values.secrets.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secrets.items }}
        - |
          objectName: {{ .keyVaultName }}
          objectType: secret
        {{- end }}
  secretObjects:
    - secretName: {{ include "${{ values.service_name }}.fullname" . }}-secrets
      type: Opaque
      data:
        {{- range .Values.secrets.items }}
        - objectName: {{ .keyVaultName }}
          key: {{ .envVar }}
        {{- end }}
{{- end }}
