apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-ingress

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice-blog.yaml
  - virtualservice-portal.yaml
  - virtualservice-portal-api.yaml
  - virtualservice-pricing-api-prod.yaml
