apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: blog-vs
  namespace: istio-ingress
spec:
  hosts:
    - "blog.chrishouse.io"
  gateways:
    - internal-gateway
  http:
    - route:
        - destination:
            host: blog.blog.svc.cluster.local
            port:
              number: 80
