apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portal-vs
  namespace: istio-ingress
spec:
  hosts:
    - "portal.chrishouse.io"
  gateways:
    - internal-gateway
    - external-gateway
  http:
    - route:
        - destination:
            host: portal-frontend.armportal-frontend.svc.cluster.local
            port:
              number: 80
