# Wildcard certificate for Istio gateway on spoke cluster
# Uses DNS-01 challenge with Cloudflare
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-chrishouse-io
  namespace: istio-ingress
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - "*.chrishouse.io"
    - "chrishouse.io"
