# ConfigMap for ARMServicePortal Backend
# Non-sensitive environment variables

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: armportal-backend
data:
  NODE_ENV: "production"
  GH_APP_ID: "2298250"
  GH_INSTALLATION_ID: "94912535"
  GH_INFRA_OWNER: "crh225"
  GH_INFRA_REPO: "ARMServicePortal"
  GH_OAUTH_CLIENT_ID: "Ov23liHgcQ7urCFXPs2k"
  FRONTEND_URL: "https://portal.chrishouse.io"
  APP_NAME: "arm-service-portal"
  APP_URL: "https://portal-api.chrishouse.io"
  ELASTICSEARCH_URL: "https://es-test-az-elk-managed-dev-5a6e80.es.eastus2.azure.elastic-cloud.com:9243"
  LOG_ANALYTICS_WORKSPACE_ID: "c200dcd8-f350-4895-99c0-1a0828fe7384"
