apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - service-entry-spoke.yaml
  - virtualservice-blog.yaml
  - virtualservice-portal.yaml
  - virtualservice-portal-api.yaml
  - wildcard-certificate.yaml
