apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - service-entry-spoke.yaml
  - virtualservice-blog.yaml
  - virtualservice-portal.yaml
  - virtualservice-portal-api.yaml
  - virtualservice-pricing-api-prod.yaml
  - virtualservice-preview-envs.yaml
  - service-entry-shared-dev.yaml
  - wildcard-certificate.yaml
  - virtualservice-customer-api-1-prod.yaml