# Service Account for Backstage with Azure Workload Identity
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: backstage
  annotations:
    azure.workload.identity/client-id: "4db95085-ec10-421b-8b04-8052ad391fcf"
  labels:
    azure.workload.identity/use: "true"
    app: backstage
