# Service Account for Backstage with Azure Workload Identity
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: backstage
  annotations:
    azure.workload.identity/client-id: "3e50729e-4a1f-42ab-aebb-9f80758b8c8d"
  labels:
    azure.workload.identity/use: "true"
    app: backstage
