# Composite Resource Definition for Azure Container Apps Environment
# The environment is required before deploying container apps
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcontainerenvironments.armportal.io
spec:
  group: armportal.io
  names:
    kind: XContainerEnvironment
    plural: xcontainerenvironments
  claimNames:
    kind: ContainerEnvironment
    plural: containerenvironments
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    environmentName:
                      type: string
                      description: Name of the container apps environment
                      pattern: '^[a-z0-9]([a-z0-9-]{0,58}[a-z0-9])?$'
                    location:
                      type: string
                      description: Azure region
                      default: "East US"
                    resourceGroupName:
                      type: string
                      description: Resource group name
                    infrastructureSubnetId:
                      type: string
                      description: Optional subnet ID for VNET integration
                    internal:
                      type: boolean
                      description: Deploy as internal (private) environment
                      default: false
                  required:
                    - environmentName
                    - resourceGroupName
              required:
                - parameters
            status:
              type: object
              properties:
                environmentId:
                  type: string
                  description: The Azure resource ID of the environment
