apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portal-api-tls
  namespace: portal-api
spec:
  secretName: portal-api-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - portal-api.chrishouse.io
