apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-api-config
  namespace: portal-api
  labels:
    app.kubernetes.io/name: portal-api
    app.kubernetes.io/component: backend
data:
  NODE_ENV: "development"
  GH_APP_ID: "2298250"
  GH_INSTALLATION_ID: "94912535"
  GH_INFRA_OWNER: "crh225"
  GH_INFRA_REPO: "ARMServicePortal"
  GH_OAUTH_CLIENT_ID: "Ov23liHgcQ7urCFXPs2k"
  FRONTEND_URL: "https://portal.chrishouse.io"
  APP_NAME: "arm-portal-dev"
  APP_URL: "https://portal-api.chrishouse.io"
  LOG_ANALYTICS_WORKSPACE_ID: "c200dcd8-f350-4895-99c0-1a0828fe7384"
