apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: portal-api-gateway
  namespace: portal-api
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - portal-api.chrishouse.io
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - portal-api.chrishouse.io
      tls:
        mode: SIMPLE
        credentialName: portal-api-tls
