apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-api-ingress
  namespace: portal-api
  labels:
    app.kubernetes.io/name: portal-api
    app.kubernetes.io/component: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portal-api.chrishouse.io
      secretName: portal-api-ingress-tls
  rules:
    - host: portal-api.chrishouse.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-api
                port:
                  number: 80
