apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portal-api

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret-provider-class.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: armportal
