apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-api
  namespace: portal-api
  labels:
    app.kubernetes.io/name: portal-api
    app.kubernetes.io/component: backend
  annotations:
    azure.workload.identity/client-id: "4db95085-ec10-421b-8b04-8052ad391fcf"
