{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  hosts:
    {{- if .Values.istio.preview.enabled }}
    - {{ .Values.istio.preview.hostname }}
    {{- else }}
    - {{ .Chart.Name }}.{{ .Values.istio.domain }}
    {{- end }}
  gateways:
    {{- if .Values.istio.crossCluster }}
    - istio-system/cross-network-gateway
    {{- else }}
    - {{ .Values.istio.gateway }}
    {{- end }}
    {{- if .Values.istio.preview.enabled }}
    - istio-system/cross-network-gateway
    {{- end }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
