name: Frontend Dev

on:
  push:
    branches: [ main ]
    paths:
      - "portal/frontend/**"

permissions:
  id-token: write
  contents: read     

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "22.x"
      VITE_API_BASE_URL: https://armportal-api-dev.kindisland-0c7a7c9a.eastus2.azurecontainerapps.io


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: portal/frontend/package-lock.json

      - name: Install dependencies
        working-directory: portal/frontend
        run: npm ci

      - name: Build
        working-directory: portal/frontend
        run: npm run build

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload static site to Storage
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_FRONTEND_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination '$web' \
            --source portal/frontend/dist \
            --overwrite true
